server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

#Fegin默认1s超时，设置超时时间
ribbon:
  ReadTimeout:  5000
  ConnectTimeout: 5000

#Fegin 开启日志
logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug

